#pragma config(Sensor, S1,     gyro,           sensorI2CHiTechnicGyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float gyroValue = 0;
float offset = 0;
float angle = 0;
float gyroRate = 0;

void gyroIntegrator();
void calibrate();

task main{
	calibrate();
	while (1){
		gyroAngle();
	}
}

void gyroAngle(){
	gyroValue = SensorRaw[gyro];
	gyroRate = gyroValue - offset;
	angle += (gyroRate / 100.0);

	displayTextLine(5, "%d\n", angle);

	wait1Msec(10);
}

void calibrate(){
	float i = 0.0;
	while (nPgmTime < 3000){
		offset += SensorRaw[gyro];
		i++;
	}
	offset /= i;
	playSound(soundBlip);
}
