#pragma config(Sensor, S1,     HTCOMP,         sensorAnalogInactive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/hitechnic-gyro.h"

float pid_Kp = 2.0;
float pid_Ki = 0.04;
float pid_Kd = 0.0;

task pidController()
{
	float pidSensorCurrentValue;

	float pidError;
	float pidLastError;
	float pidIntegral;
	float pidDerivative;
	float pidDrive;

	pidLastError = 0;
	pidIntegral = 0;

	while (true){
		pidSensorCurrentValue = HTMCsetTarget(HTCOMP) * PID_SENSOR_SCALE;

		pidError = pidSensorCurrentValue - pidRequestedValue;

		if (pid_Ki != 0){
			if (abs(pidError) < PID_INTEGRAL_LIMIT){
				pidIntegral = pidIntegral + pidError;

			else
				pidIntegral = 0;
			}

		else
			pidIntegral = 0;

		pidDerivative = pidError - pidLastError;
		pidLastError = pidError;

		pidDrive = (pid_Kp * pidError) + (pid_Ki * pidIntegral) + (pid_Kd * pidDerivative);

		if (pidDrive > PID_DRIVE_MAX)
			pidDrive = PID_DRIVE_MAX;
		if (pidDrive < PID_DRIVE_MIN)
			pidDrive = PID_DRIVE_MIN;

		motor[ PID_MOTOR_INDEX ] = pidDrive * PID_MOTOR_SCALE;

		}

	else {

		pidError = 0;
		pidLastError = 0;
		pidIntegral = 0;
		pidDerivative = 0;
		motor[ PID_MOTOR_INDEX ] = 0;
	}

	wait1Msec( 25 );

}



task main()
{

	StartTask( pidController );

	while (true)
	{
		pidRequestedValue = 90;
		wait1Msec(50);

}
