#pragma config(Sensor, S1,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     hallEffect,     sensorAnalog)
#pragma config(Motor,  motorB,          motorLeft,     tmotorNXT, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          motorRight,    tmotorNXT, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

static int masterPower = 120;
static int slavePower = 120;
static int distCount = 0;

task driveStraight()
{

  int error = 0;

  int kp = 5;

  nMotorEncoder[motorLeft] = 0;
  nMotorEncoder[motorRight] = 0;

  while(true)
  {

    motor[motorLeft] = masterPower;
    motor[motorRight] = slavePower;

    error = nMotorEncoder[motorLeft] - nMotorEncoder[motorRight];

    slavePower += error / kp;

    distCount += nMotorEncoder[motorLeft];

    nMotorEncoder[motorLeft] = 0;
  	nMotorEncoder[motorRight] = 0;

    wait1Msec(100);

  }
}

task main()
{

	int hallCal = 0;

	hallCal = SensorValue[hallEffect];

	startTask(driveStraight);

	while (distCount < 500){
	}

	stopTask(driveStraight);

	masterPower = 60;
	slavePower = 60;

	startTask(driveStraight);

	while (fabs(SensorValue[hallEffect]- hallCal) < 100){
		displayString(4, "%d", SensorValue[hallEffect]- hallCal);

	}

	stopTask(driveStraight);

	motor[motorLeft] = 0;
  motor[motorRight] = 0;

	wait1Msec(1000);

	for (int i = 0; i < 3; i++){
		playSound(soundBlip);
		wait10Msec(10);
	}

}
