#pragma config(Sensor, S1,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorB,          motorLeft,     tmotorNXT, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          motorRight,    tmotorNXT, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "gyroPid.h"

task main () {

	pidRequestedValue = 30;
  startTask(pidController);

  while (fabs(angle - pidRequestedValue) > .1)
  {
	}

	stopTask(pidController);

	wait10Msec(1);

	nMotorEncoder[motorLeft] = 0;
	nMotorEncoder[motorRight] = 0;
	nMotorEncoderTarget[motorLeft] = in2encoder(12);
	nMotorEncoderTarget[motorRight] = in2encoder(12);

	motor[motorLeft] = 127;
	motor[motorRight] = 127;

	while(nMotorRunState[motorLeft] != runStateIdle && nMotorRunState[motorRight] != runStateIdle)
	{
	}
	motor[motorLeft] = 0;
	motor[motorRight] = 0;

}
