#pragma config(Sensor, S1,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorB,          motorLeft,     tmotorNXT, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          motorRight,    tmotorNXT, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "gyroPid.h"

static int masterPower = 120;
static int slavePower = 120;
static int distCount = 0;

task driveStraight()
{

  int error = 0;

  int kp = 5;

  nMotorEncoder[motorLeft] = 0;
  nMotorEncoder[motorRight] = 0;

  while(true)
  {

    motor[motorLeft] = masterPower;
    motor[motorRight] = slavePower;

    error = nMotorEncoder[motorLeft] - nMotorEncoder[motorRight];

    slavePower += error / kp;

    distCount += nMotorEncoder[motorLeft];

    nMotorEncoder[motorLeft] = 0;
  	nMotorEncoder[motorRight] = 0;

    wait1Msec(100);

  }
}

task main () {

	pidRequestedValue = 30;
  startTask(pidController);

  while (fabs(angle - pidRequestedValue) > .1)
  {
	}

	stopTask(pidController);

	wait10Msec(1);

	startTask(driveStraight);
	while (distCount < 2 * 0.3048 * 1000){ // 2 meters
	}

	stopTask(driveStraight);

	motor[motorLeft] = 0;
	motor[motorRight] = 0;

}
