#pragma config(Sensor, S1,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorB,          motorLeft,     tmotorNXT, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          motorRight,    tmotorNXT, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "gyroPid.h"

static int masterPower = 120;
static int slavePower = 120;
static int distCount = 0;

task driveStraight()
{

	int error = 0;

	int kp = 5;

	nMotorEncoder[motorLeft] = 0;
	nMotorEncoder[motorRight] = 0;


	motor[motorLeft] = masterPower;
	motor[motorRight] = slavePower;

	error = nMotorEncoder[motorLeft] - nMotorEncoder[motorRight]; // find diference between two motor positions

	slavePower += error / kp; // adjust slave power to match master speed

	distCount += nMotorEncoder[motorLeft]; // sum total distance

	nMotorEncoder[motorLeft] = 0; // reset encoders at end of loop
	nMotorEncoder[motorRight] = 0;

	wait1Msec(50);
}

void driveUntil(int distance){

	//take distance in meters
	distCount = 0;

	startTask(driveStraight);
	while (distCount < fabs(distance) * 0.34 * 1000){
	}

	stopTask(driveStraight);

	motor[motorLeft] = 0;
	motor[motorRight] = 0;
}

task main () {

	calibrate();

	pidRequestedValue = -30;
  startTask(pidController);

  while (fabs(angle - pidRequestedValue) > .1)
  {
	}

	stopTask(pidController);

	wait1Msec(10);



	driveUntil(4);



	motor[motorLeft] = 0;
	motor[motorRight] = 0;

}
